# Converting the file to the csv format

In [1]:
import zipfile

zip_path = r"C:\Users\jyots\Downloads\no_pii_grievance.json.zip"
extract_path = r"C:\Users\jyots\Downloads"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [2]:
import pandas as pd

df = pd.read_json(r"C:\Users\jyots\Downloads\no_pii_grievance.json")

In [3]:
df.to_csv(r"C:\Users\jyots\Downloads\government_grievance.csv", index=False)

# Preprocessing the data

In [4]:
df.head()

,_id,CategoryV7,DiaryDate,UserCode,closing_date,dist_name,org_code,pincode,recvd_date,registration_no,remarks_text,resolution_date,sex,state,subject_content_text,v7_target
0,MORLY/E/2023/0000001,11578.0,{'$date': '2023-01-01T00:00:19.977Z'},110124.0,{'$date': '2023-01-04T00:00:00Z'},North 24 Parganas,MORLY,700130,{'$date': '2023-01-01T00:00:19.977Z'},MORLY/E/2023/0000001,"As per railway record, there is no authoriz...",{'$date': '2023-01-04T00:00:00Z'},M,WB,"Railways, ( Railway Board) >> Miscellaneous\r\...",No
1,GOVUP/E/2023/0000001,NaN,{'$date': '2023-01-01T00:01:29.78Z'},45427.0,{'$date': '2023-01-24T00:00:00Z'},NaN,GOVUP,203001,{'$date': '2023-01-01T00:01:28.567Z'},GOVUP/E/2023/0000001,NaN,NaN,M,UP,XAXPX/X/X0X2X4X0X0\tREGARDING CBCID INSPECTION...,NaN
2,MOLBR/E/2023/0000001,2369.0,{'$date': '2023-01-01T00:01:45.593Z'},1356254.0,{'$date': '2023-01-12T00:00:00Z'},Hyderabad,MOLBR,500023,{'$date': '2023-01-01T00:01:45.593Z'},MOLBR/E/2023/0000001,"Sir/Madam, With reference to Grievance no. XO...",{'$date': '2023-01-12T00:00:00Z'},M,TG,Labour and Employment >> PF Withdrawal >> Othe...,No
3,MOLBR/E/2023/0000002,2379.0,{'$date': '2023-01-01T00:02:07.247Z'},1092136.0,{'$date': '2023-01-06T00:00:00Z'},Nagpur,MOLBR,440001,{'$date': '2023-01-01T00:02:07.247Z'},MOLBR/E/2023/0000002,Please submit establishment clarification let...,{'$date': '2023-01-06T00:00:00Z'},M,MH,Labour and Employment >> Pension >> Others\r\n...,No
4,GOVUP/E/2023/0000002,NaN,{'$date': '2023-01-01T00:02:25.663Z'},45427.0,{'$date': '2023-01-24T00:00:00Z'},NaN,GOVUP,203001,{'$date': '2023-01-01T00:02:24.913Z'},GOVUP/E/2023/0000002,NaN,NaN,M,UP,XAXPX/X/X0X2X4X0X8\tREGARDING CBCID INSPECTION...,NaN

In [5]:
df.shape

(175784, 16)

In [6]:
df.isnull().sum()

_id                          0
CategoryV7              112162
DiaryDate                    0
UserCode                 77687
closing_date             13419
dist_name                52976
org_code                   383
pincode                  14282
recvd_date                   0
registration_no              0
remarks_text             68880
resolution_date          68880
sex                          0
state                      263
subject_content_text         0
v7_target               119121
dtype: int64

In [7]:
df.drop(['CategoryV7','DiaryDate','UserCode','closing_date','dist_name','pincode','recvd_date','registration_no','remarks_text'
         ,'resolution_date','sex','state','v7_target'], axis=1, inplace=True)

In [8]:
df.drop(['_id'], axis=1, inplace=True)

In [9]:
df.head()

  org_code                               subject_content_text
0    MORLY  Railways, ( Railway Board) >> Miscellaneous\r\...
1    GOVUP  XAXPX/X/X0X2X4X0X0\tREGARDING CBCID INSPECTION...
2    MOLBR  Labour and Employment >> PF Withdrawal >> Othe...
3    MOLBR  Labour and Employment >> Pension >> Others\r\n...
4    GOVUP  XAXPX/X/X0X2X4X0X8\tREGARDING CBCID INSPECTION...

In [10]:
df['org_code'].nunique()

200

In [11]:
df['org_code'].unique()

array(['MORLY', 'GOVUP', 'MOLBR', 'MODEF', 'DEPOJ', 'MEAPD', 'DORLD',
       'DOTEL', 'GOVTG', 'MINHA', 'MOPRJ', 'DTOUR', 'GOVTN', 'GOVAS',
       'DPLNG', 'CBODT', 'DARPG', 'DODAF', 'GOVMP', 'DEABD', 'MINIT',
       'GOVHY', 'MOIAB', 'GOVJH', 'DHLTH', 'DLGLA', 'MTRBL', 'DOSEL',
       'DOPAT', 'GOVMH', 'DDESW', 'LGVED', 'DOCAF', 'DOCOM', 'DOEAF',
       'GOVUC', 'DPOST', 'DOSIR', 'GOVCC', 'MOEAF', 'MORTH', 'GNCTD',
       'GOVRJ', 'MOCOP', 'GOVGJ', 'GOVBH', 'DOURD', 'UIDAI', 'AYUSH',
       'DOAAC', 'DATOM', 'MPANG', 'DSEHE', 'DOSAT', 'DEAID', 'MINWR',
       'DSPRT', 'DCOYA', 'FADSS', 'MPOWR', 'GOVTR', 'MOSJE', 'CBOEC',
       'DOLDR', 'GOVPB', 'DOSKD', 'DOFPD', 'DOWCD', 'MOCAV', 'DCLTR',
       'GOVKL', 'MINPA', 'DPHAM', 'MOYAS', 'GOVJK', 'DHIND', 'DEAPR',
       'DHRES', 'MOSPI', 'MMSME', 'DODIV', 'DOEXP', 'GOVOR', 'DDRDO',
       'GOVAN', 'GOVWB', 'AGPS5', 'BSFOR', 'CGAT4', 'CGATP', 'CLC10',
       'CMPFO', None, 'DMAFF', 'DOARE', 'DOCPC', 'DODWS', 'DOFPI',
       'DOFZR', 'DOIPP', 'DOPPW', 'DORVU', 'MEAPM', 'DPUBE', 'GOVAP',
       'GOVCH', 'GOVDN', 'GOVGO', 'GOVHP', 'GOVKN', 'GOVMG', 'GOVMZ',
       'GOVNL', 'GOVPY', 'GOVSK', 'MOMAF', 'PMOPG', 'RBSP4', 'SBCHE',
       'SCRLY', 'TMBHR', 'WRCCG', 'GOVAR', 'MCOAL', 'MSHPG', 'CAGAO',
       'DFSHR', 'ARNPG', 'MONRE', 'DOAHD', 'MMINE', 'CBS01', 'CGMUW',
       'DDPRO', 'GOVLK', 'POLII', 'PRIW1', 'PRIW3', 'PRSEC', 'PUFCI',
       'SC123', 'USPP5', 'MTXTL', 'CEAMP', 'CLC07', 'DBIOT', 'DL172',
       'DTDDG', 'ECCOM', 'GOVDD', 'GOVLD', 'GOVMN', 'KVSDL', 'PESIC',
       'PRIW2', 'RDRC3', 'RDRCD', 'RDRC2', 'RE1PG', 'DSPAC', 'DONER',
       'CGDAN', 'CMASM', 'DDGTM', 'DOCND', 'JJMIV', 'MOSTL', 'USIOC',
       'CGMBH', 'RE5PG', 'SBDEL', 'USRPK', 'DEACM', 'ATPOR', 'SBCRD',
       'ALCK1', 'IRSEC', 'CLC01', 'LEOR2', 'MTNLD', 'NERLY', 'BPNLO',
       'BSF74', 'SWRLY', 'JSOLD', 'RBSP6', 'CGAT8', 'NCL01', 'GUJPC',
       'NWRLY', 'AKVPG', 'KN172', 'RDNSP', 'TMUTA', 'UDPCR', 'CERLY',
       'CHQSO', 'CS123', 'CS234', 'DTEST', 'SSCNP'], dtype=object)

In [12]:
df['org_code'].value_counts()

org_code
PMOPG    49882
MOLBR    11471
DEABD    10392
GOVUP     8495
DEAID     7803
         ...
TMBHR        1
SBCHE        1
CS234        1
DTEST        1
CGMUW        1
Name: count, Length: 200, dtype: int64

In [13]:
counts = df['org_code'].value_counts()

df = df[df['org_code'].isin(counts[counts >= 1000].index)]

In [14]:
df['org_code'].nunique()

28

In [15]:
df['org_code'].unique()

array(['MORLY', 'GOVUP', 'MOLBR', 'DEPOJ', 'MEAPD', 'DORLD', 'DOTEL',
       'MINHA', 'GOVAS', 'CBODT', 'DARPG', 'DEABD', 'GOVHY', 'DHLTH',
       'DOPAT', 'DDESW', 'DOCAF', 'DPOST', 'MORTH', 'GOVRJ', 'GOVGJ',
       'DOURD', 'UIDAI', 'DOAAC', 'MPANG', 'DEAID', 'DOPPW', 'PMOPG'],
      dtype=object)

In [16]:
df = df[~df['org_code'].isin(['GOVUP','GOVAS','GOVHY','GOVRJ','GOVGJ'])]

In [17]:
df['org_code'].unique()

array(['MORLY', 'MOLBR', 'DEPOJ', 'MEAPD', 'DORLD', 'DOTEL', 'MINHA',
       'CBODT', 'DARPG', 'DEABD', 'DHLTH', 'DOPAT', 'DDESW', 'DOCAF',
       'DPOST', 'MORTH', 'DOURD', 'UIDAI', 'DOAAC', 'MPANG', 'DEAID',
       'DOPPW', 'PMOPG'], dtype=object)

In [18]:
df['org_code'].value_counts()

org_code
PMOPG    49882
MOLBR    11471
DEABD    10392
DEAID     7803
DOAAC     6501
CBODT     6323
DARPG     5597
DOTEL     4623
DPOST     4559
DOPPW     4414
MORLY     3069
MINHA     3037
DOPAT     2060
DOURD     1887
MORTH     1643
DEPOJ     1514
DHLTH     1378
DORLD     1246
UIDAI     1217
DDESW     1135
MPANG     1111
DOCAF     1059
MEAPD     1040
Name: count, dtype: int64

In [19]:
df.isnull().sum()

org_code                0
subject_content_text    0
dtype: int64

In [20]:
balanced_data = []
for org, group in df.groupby('org_code'):
    unique_group = group.drop_duplicates() 
    if len(unique_group) >= 2000:
        group_balanced = unique_group.sample(n=2000, random_state=42)
    else:
        remaining = 2000 - len(unique_group)
        extra = unique_group.sample(n=remaining, replace=True, random_state=42)
        group_balanced = pd.concat([unique_group, extra])
    balanced_data.append(group_balanced)
balanced_df = pd.concat(balanced_data)

In [21]:
balanced_df.head()

       org_code                               subject_content_text
90577     CBODT  Central Board of Direct Taxes (Income Tax) >> ...
56825     CBODT  Central Board of Direct Taxes (Income Tax) >> ...
102105    CBODT  Central Board of Direct Taxes (Income Tax) >> ...
51811     CBODT  Central Board of Direct Taxes (Income Tax) >> ...
146046    CBODT  Central Board of Direct Taxes (Income Tax) >> ...

In [22]:
balanced_df['org_code'].value_counts()

org_code
CBODT    2000
DOTEL    2000
PMOPG    2000
MPANG    2000
MORTH    2000
MORLY    2000
MOLBR    2000
MINHA    2000
MEAPD    2000
DPOST    2000
DOURD    2000
DORLD    2000
DARPG    2000
DOPPW    2000
DOPAT    2000
DOCAF    2000
DOAAC    2000
DHLTH    2000
DEPOJ    2000
DEAID    2000
DEABD    2000
DDESW    2000
UIDAI    2000
Name: count, dtype: int64

In [23]:
balanced_df['org_code'].nunique()

23

In [24]:
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [25]:
balanced_df.head()

  org_code                               subject_content_text
0    DORLD  Rural Development >> Pradhan Mantri Awaas Yoja...
1    PMOPG  *Appeal From Bank Pensioner*\r\n\r\n\r\nShri N...
2    MPANG  Petroleum and Natural Gas >> PNG related >> De...
3    DOURD  Housing and Urban Affairs >> HUDCO (Housing an...
4    DOAAC  Agriculture and Farmers Welfare >> PMKISAN rel...

# The cleaning part of the text

In [26]:
pip install nltk indic-nlp-library

Requirement already satisfied: nltk in c:\users\jyots\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: indic-nlp-library in c:\users\jyots\anaconda3\lib\site-packages (0.92)
Requirement already satisfied: click in c:\users\jyots\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\jyots\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jyots\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\jyots\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: sphinx-argparse in c:\users\jyots\anaconda3\lib\site-packages (from indic-nlp-library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in c:\users\jyots\anaconda3\lib\site-packages (from indic-nlp-library) (3.1.0)
Requirement already satisfied: morfessor in c:\users\jyots\anaconda3\lib\site-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in c:\users\jyots\anaconda3\lib\site-packages (from indic-nlp-library) (2.3.3)
Requirement already satisfied: numpy in c:\users\jyots\anaconda3\lib\site-packages (from indic-nlp-library) (2.3.5)
Requirement already satisfied: colorama in c:\users\jyots\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jyots\anaconda3\lib\site-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jyots\anaconda3\lib\site-packages (from pandas->indic-nlp-library) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jyots\anaconda3\lib\site-packages (from pandas->indic-nlp-library) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jyots\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.17.0)
Requirement already satisfied: sphinx>=5.1.0 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx-argparse->indic-nlp-library) (8.2.3)
Requirement already satisfied: docutils>=0.19 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx-argparse->indic-nlp-library) (0.21.2)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.19.2)
Requirement already satisfied: snowballstemmer>=2.2 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.1)
Requirement already satisfied: babel>=2.13 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.17.0)
Requirement already satisfied: alabaster>=0.7.14 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.5)
Requirement already satisfied: roman-numerals-py>=1.0.0 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.0)
Requirement already satisfied: packaging>=23.0 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (25.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jyots\anaconda3\lib\site-packages (from Jinja2>=3.1->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jyots\anaconda3\lib\site-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jyots\anaconda3\lib\site-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jyots\anaconda3\lib\site-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jyots\anaconda3\lib\site-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2026.1.4)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in c:\users\jyots\anaconda3\lib\site-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [43]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jyots\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jyots\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jyots\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [28]:
english_stopwords = set(stopwords.words('english'))

In [29]:
hindi_stopwords = {
'और','का','की','के','है','हैं','को','से','पर','यह','था','थे','कर','भी',
'में','तो','ही','लेकिन','अगर','जब','तक','क्यों','कौन','क्या'
}

In [30]:
all_stopwords = english_stopwords.union(hindi_stopwords)

In [31]:
lemmatizer = WordNetLemmatizer()

In [32]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\u0900-\u097F\s]', '', text)
    words = text.split()
    cleaned_words = []
    for word in words:
        if word not in all_stopwords:
            if re.match(r'[a-zA-Z]+$', word):
                word = lemmatizer.lemmatize(word)
            cleaned_words.append(word)
    return " ".join(cleaned_words)

In [33]:
balanced_df['subject_content_text'].apply(clean_text)

0        rural development pradhan mantri awaas yojana ...
1        appeal bank pensioner shri narendra modi honor...
2        petroleum natural gas png related delay instal...
3        housing urban affair hudco housing urban devel...
4        agriculture farmer welfare pmkisan related iss...
                               ...
45995    grievance status registration number xexoxxxxx...
45996    unique identification authority india non upda...
45997    road transport highway policiy related land ac...
45998    central board direct tax income tax direct tax...
45999    th installment credit th installment credited ...
Name: subject_content_text, Length: 46000, dtype: object

In [34]:
balanced_df.head(10)

  org_code                               subject_content_text
0    DORLD  Rural Development >> Pradhan Mantri Awaas Yoja...
1    PMOPG  *Appeal From Bank Pensioner*\r\n\r\n\r\nShri N...
2    MPANG  Petroleum and Natural Gas >> PNG related >> De...
3    DOURD  Housing and Urban Affairs >> HUDCO (Housing an...
4    DOAAC  Agriculture and Farmers Welfare >> PMKISAN rel...
5    MPANG  Petroleum and Natural Gas >> Petrol Pump Allot...
6    DHLTH  सेवा में ,\r\n स्वास्थ्य एवं परिवार कल्याण मंत...
7    MEAPD  The Passport Officer,\n\nMuzaffarnagar up \n\n...
8    PMOPG  Subject:  Is Time precious and people will pay...
9    DOAAC  Agriculture and Farmers Welfare >> PMKISAN rel...